spring:
  application:
    name: firstspringbatch
  config:
    activate:
      on-profile: test
  batch:
    job:
      enabled: false
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batch
